basePath: /
host: localhost:8080
info:
  contact: {}
  version: "1.0"
paths:
  /exchange/{currency}:
    get:
      description: Get Exchange
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get Exchange rate for currency
swagger: "2.0"
